package sparsetableproject1;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import static sparsetableproject1.StudentP.meth2;
public class AdminP extends javax.swing.JFrame {
//static AdminP admin =new AdminP();
public static StudentP student =new StudentP();
static AdminP admin=new AdminP();
    // Swing components
    /**
     * Creates new form AdminP
     */
    public AdminP() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxgetstu = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        courseIField = new javax.swing.JTextField();
        remCourseButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        addStudentButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        addID = new javax.swing.JTextField();
        jButtonaddinsys = new javax.swing.JButton();
        jComboBoxrem = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminP.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Student ID :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Get Courses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Select Course :");

        jComboBoxgetstu.setFocusTraversalPolicyProvider(true);
        jComboBoxgetstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxgetstuActionPerformed(evt);
            }
        });

        jButton2.setText("Get Students");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Course Name :");

        remCourseButton.setText("Remove");
        remCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remCourseButtonActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Adminstrator");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(12, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(234, 86));
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Student ID :");

        addStudentButton.setText("Add Student");
        addStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentButtonMouseClicked(evt);
            }
        });
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mariam Habshi\\Downloads\\Server (1).jpg")); // NOI18N
        jLabel7.setText("jLabel7");

        addID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIDActionPerformed(evt);
            }
        });

        jButtonaddinsys.setText("Add");
        jButtonaddinsys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddinsysActionPerformed(evt);
            }
        });

        jComboBoxrem.setFocusTraversalPolicyProvider(true);
        jComboBoxrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxremActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Select Course :");

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPLayout = new javax.swing.GroupLayout(AdminP);
        AdminP.setLayout(AdminPLayout);
        AdminPLayout.setHorizontalGroup(
            AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPLayout.createSequentialGroup()
                        .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPLayout.createSequentialGroup()
                                .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(addID)
                                    .addComponent(jComboBoxrem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(courseIField, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addStudentButton)
                                    .addComponent(jButtonaddinsys, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(remCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AdminPLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxgetstu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addGap(183, 183, 183))
                    .addGroup(AdminPLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AdminPLayout.createSequentialGroup()
                                .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(AdminPLayout.createSequentialGroup()
                                        .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(AdminPLayout.createSequentialGroup()
                                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5))
                                            .addGroup(AdminPLayout.createSequentialGroup()
                                                .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(AdminPLayout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPLayout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jLabel2)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(188, 188, 188))))))
        );
        AdminPLayout.setVerticalGroup(
            AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addGroup(AdminPLayout.createSequentialGroup()
                        .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Back))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jComboBoxgetstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseIField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jButtonaddinsys))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(remCourseButton)
                            .addComponent(jComboBoxrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AdminPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(addStudentButton)))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminP, javax.swing.GroupLayout.PREFERRED_SIZE, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void printStudentCourses(int idd){
        if(meth2.checkId(idd)!=null){
            StudentNodes.csNode tempNode = meth2.checkId(idd).linkWithCourse;
            if(tempNode!=null){
            while(tempNode!=null){
                admin.jTextArea2.append( tempNode.course+ "\n");
                tempNode= tempNode.nextDown;
            }}else{
                JOptionPane.showMessageDialog(this,"There's no courses");
            }
        
        }else{
            JOptionPane.showMessageDialog(this,"ID not found");
        }
    } 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(!admin.jTextField1.getText().equals("")){        
        jTextArea2.setText("");
// TODO add your handling code here:
        //printStudentCourses(Integer.parseInt(jTextField1.getText()));
        String inputText = admin.jTextField1.getText().trim();

    if (!inputText.isEmpty()) {
        try {
            int studentId = Integer.parseInt(inputText);
            printStudentCourses(studentId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid student ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please enter a student ID.", "Error", JOptionPane.ERROR_MESSAGE);
    }}else {
       JOptionPane.showMessageDialog(this, "Please enter a student ID.");
       }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void printCoursStudents(String c){
        if(meth2.isCourseExist(c)!=null){
            StudentNodes.csNode tempNode = meth2.isCourseExist(c).linkWithStudent;
            if(tempNode!=null){
                while(tempNode!=null){
                admin.jTextArea1.append( tempNode.id+ "\n");
                tempNode= tempNode.nextRight;
            }
            }else{
                JOptionPane.showMessageDialog(this,"this course has no students");
            }
        
        }else{
            JOptionPane.showMessageDialog(this,"this course is not exist");
        }
    
    
    
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextArea1.setText("");
        printCoursStudents((String)admin.jComboBoxgetstu.getSelectedItem());     
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBoxgetstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxgetstuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxgetstuActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        
         System.mysys.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
   if(!admin.addID.getText().equals("")){
    meth2.addStudent(Integer.parseInt(admin.addID.getText()));
    JOptionPane.showMessageDialog(this,"Student has been added to system");
    addID.setText("");
    }else{
    JOptionPane.showMessageDialog(this,"You should enter id");
    }
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void addIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIDActionPerformed

    private void addStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentButtonMouseClicked
   /*public void deleteCourseFromSystem(String c){

        if(StudentNodes.callmethod.isCourseExist(c)!=null){ //if course exist 
            StudentNodes.cNode tempCourse = StudentNodes.callmethod.isCourseExist(c);
            StudentNodes.cNode temp = StudentNodes.callmethod.courseHead;
            while(temp.next!=tempCourse){
                temp=temp.next;
            }
            //then temp = prev course that i wanna delete
           if(tempCourse.linkWithStudent==null){ //no students assigned to this course
               if(tempCourse.next!=null)
                  temp.next=tempCourse.next;
               else{
                  StudentNodes.callmethod.courseTail=temp; 
               }
           }else{ //there is students assigned to this course
               StudentNodes.csNode csTemp = tempCourse.linkWithStudent; // first student assigned this course
               while(csTemp!=null){
                   if(csTemp.firstUp!=null){ //this course was first course to this student
                       csTemp.firstUp.linkWithCourse =csTemp.nextDown;
                       csTemp.nextDown.firstUp = csTemp.firstUp;
                       csTemp.up=null;
                       csTemp.nextDown=null;
                   }else{ //this course is between other courses
                       csTemp.up.nextDown = csTemp.nextDown;
                       csTemp.nextDown.up = csTemp.up;
                       csTemp.up=null;
                       csTemp.nextDown=null;
                   }
                   csTemp = csTemp.nextRight;
               }
               
               if(tempCourse.next!=null)
                  temp.next=tempCourse.next;
               else
                  StudentNodes.callmethod.courseTail=temp; 
        
                    }
           jComboBoxgetstu.removeItem(c);
       jComboBoxrem.removeItem(c);
       student.jComboBox1instu.removeItem(c);
        }
        else{ 
            JOptionPane.showMessageDialog(this,"Course is not exist");
    }*/
    public void deleteCourseFromSystem(String c){
        if(meth2.isCourseExist(c)!=null){ //if course exist 
            StudentNodes.cNode tempCourse = meth2.isCourseExist(c);
            StudentNodes.cNode temp = meth2.courseHead;
            while(temp.next!=tempCourse && temp!=tempCourse){
                temp=temp.next;
            }
            
            //then temp = prev course that i wanna delete
           if(tempCourse.linkWithStudent==null){ //no students assigned to this course
               if(tempCourse.next!=null)
                  temp.next=tempCourse.next;
               else{
                  meth2.courseTail=temp;
                  tempCourse=null;
               }
           }else{ //there is students assigned to this course
               StudentNodes.csNode csTemp = tempCourse.linkWithStudent; // first student assigned this course
               temp.linkWithStudent=null;
               while(csTemp!=null){
                   if(csTemp.firstUp!=null){ //this course was first course to this student
                       csTemp.firstUp.linkWithCourse =csTemp.nextDown;
                       if(csTemp.nextDown!=null){
                       csTemp.nextDown.firstUp = csTemp.firstUp;
                       }else{
                           csTemp.firstUp.linkWithCourse=null;
                       }
                       csTemp.up=null;
                       csTemp.nextDown=null;
                   }else{ //this course is between other courses
                       csTemp.up.nextDown = csTemp.nextDown;
                       if(csTemp.nextDown!=null){
                           csTemp.nextDown.up = csTemp.up;
                       }else{
                           csTemp.up.nextDown=null;
                       }
                       
                       csTemp.up=null;
                       csTemp.nextDown=null;
                   }
                   csTemp = csTemp.nextRight;
               }
               
               
               if(tempCourse.next!=null){
                  temp.next=tempCourse.next;
                  if(temp==tempCourse){
                      meth2.courseHead=temp.next;
                  }
               }else{
                  meth2.courseTail=temp; 
                  if(temp==tempCourse){
                      meth2.courseHead=temp.next;
                  }
           }}
        }else{ 
            JOptionPane.showMessageDialog(this, "course is not exist");
        }
    }

    private void remCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remCourseButtonActionPerformed
        // TODO add your handling code here:
        String selectedValue = (String)jComboBoxrem.getSelectedItem();
        meth2.deleteCourseFromSystem(selectedValue);
        jComboBoxgetstu.removeItem(selectedValue);
    jComboBoxrem.removeItem(selectedValue);
    }//GEN-LAST:event_remCourseButtonActionPerformed

    private void jButtonaddinsysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddinsysActionPerformed
    if(!courseIField.getText().equals("")){
     // TODO add your handling code here:
    meth2.addCourseInSystem(admin.courseIField.getText());
    JOptionPane.showMessageDialog(this, "Course has been added successfully");
     

    // Update JComboBox in the current frame
    jComboBoxgetstu.addItem(admin.courseIField.getText());
    jComboBoxrem.addItem(admin.courseIField.getText());
    // Update JComboBox in StudentP
     courseIField.setText(""); }
    else{JOptionPane.showMessageDialog(this, "You should enter course name");}
    }//GEN-LAST:event_jButtonaddinsysActionPerformed

    private void jComboBoxremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxremActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminP;
    private javax.swing.JButton Back;
    private javax.swing.JTextField addID;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JTextField courseIField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonaddinsys;
    public javax.swing.JComboBox<String> jComboBoxgetstu;
    public javax.swing.JComboBox<String> jComboBoxrem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton remCourseButton;
    // End of variables declaration//GEN-END:variables
}
